### ISSUE TITLE
problem about root/err

### ISSUE THREAD

**Issue by QX-N** [wey-gu/nebulagraph-yelp-frauddetection#1]
Sorry to bother you, but I have a problem, as shown in the picture, when I  run this  code 
docker run --rm -ti \
>  --network=nebula-net \
>  -v ${PWD}/yelp_nebulagraph_importer.yaml:/root/importer.yaml \
>  -v ${PWD}/data:/root \
>  vesoft/nebula-importer:v3.1.0 \
>  --config /root/importer.yaml

![image](https://github.com/wey-gu/nebulagraph-yelp-frauddetection/assets/108463784/995a3082-9de3-4dcf-ad00-1770d02906be)
How can I solve it?

**Comment by QX-N** [comment]
I run this code in Ubuntu 20.04, and I bootstrap a NebulaGraph with Nebula-UP successfully.

**Comment by QX-N** [comment]
OK， I solved this problem with nebulagraphv3.2.0.

**Comment by wey-gu** [comment]
Oh, it failed on newer version?
