### ISSUE TITLE
failed to import data with this yaml file and nebula-importer-v3.1.0 docker container

### ISSUE THREAD

**Issue by SoHappyZkx** [wey-gu/nebulagraph-yelp-frauddetection#2]
[ERROR] clientpool.go:158: Client(1) fails to execute commands (USE `yelp`;), error: failed to execute: Session has been released。
and when i use the same method to import another dataset [fraud-detection-datagen] it shows

2023/08/15 01:14:11 Client(0) fails to execute commands (CREATE SPACE frauddetection (partition_num = 5, replica_factor = 1, vid_type = FIXED_STRING(32)); USE frauddetection; CREATE TAG corp (corp_name string, phone_num string, is_risky string, risk_comment string); CREATE TAG application (apply_agent_id string, apply_date date, application_uuid string, approval_status string, application_type string, rejection_reason string); CREATE TAG phone_num (phone_num string); CREATE TAG device (device_id string); CREATE TAG person (name string); CREATE TAG louvain (louvain int); CREATE TAG applicant (name string, gender string, birth date, addr string, degree string, occupation string, year_salary string, is_risky string, risk_comment string); CREATE EDGE applied_for_loan (start_time date);  CREATE EDGE with_phone_num (start_time date); CREATE EDGE is_related_to (start_time date, level int); CREATE EDGE worked_for (start_time date); CREATE EDGE used_device (start_time date); CREATE TAG INDEX louvain_index on louvain(louvain);
), response error code: -1005, message: Existed!

**Comment by SoHappyZkx** [comment]
I  solved the problem with the lastest version container（nebula-importerv4.0.0 ）and new yaml template.

**Comment by wey-gu** [comment]
> I solved the problem with the lastest version container（nebula-importerv4.0.0 ）and new yaml template.

feel free to contribute the one that's working with importer 4.0.0 :)
